[tool.black]
line-length = 500
target-version = ['py39', 'py310', 'py311']
extend-exclude = '''
/(
  \.venv
  | venv
  | materials_env
  | \.pytest_cache
  | htmlcov
  | tests       
)/
'''


[tool.isort]
profile = "black"
line_length = 500
skip = [".venv", "venv", "materials_env", ".pytest_cache"]
